# BASADO en el dockerfile oficial de nestjs 
# https://docs.nestjs.com/deployment#dockerizing-your-application
FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main"]